# Generated by Django 2.2 on 2022-02-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JavaStepByStep', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentator', models.CharField(max_length=50)),
                ('reviewed', models.CharField(max_length=50)),
                ('comment', models.TextField()),
                ('response', models.TextField()),
                ('comment_time', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
