# Generated by Django 2.2 on 2022-02-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JavaStepByStep', '0002_auto_20220205_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='response',
            field=models.TextField(null=True),
        ),
    ]
