# Generated by Django 2.2 on 2022-02-06 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JavaStepByStep', '0004_auto_20220206_1604'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
