# Generated by Django 2.2 on 2022-02-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JavaStepByStep', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='project',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
