# Generated by Django 2.2 on 2022-02-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JavaStepByStep', '0007_comment_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='project',
            field=models.TextField(null=True),
        ),
    ]
