# Generated by Django 2.2 on 2022-02-16 06:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('JavaStepByStep', '0008_auto_20220206_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(null=True)),
                ('content', models.TextField(null=True)),
                ('step1', models.TextField(null=True)),
                ('step2', models.TextField(null=True)),
                ('step3', models.TextField(null=True)),
                ('project_CreateTime', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
