# Generated by Django 2.2 on 2022-03-01 13:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('JavaStepByStep', '0009_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.TextField()),
                ('file', models.TextField()),
                ('file_UploadTime', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
