# Generated by Django 2.2 on 2022-03-03 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JavaStepByStep', '0011_auto_20220301_2201'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='StudentFile',
        ),
    ]
