# Generated by Django 2.2 on 2022-03-03 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JavaStepByStep', '0012_auto_20220303_1702'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentFile',
            new_name='File',
        ),
    ]
