# Generated by Django 2.2 on 2022-03-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JavaStepByStep', '0013_auto_20220303_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file',
        ),
        migrations.AddField(
            model_name='file',
            name='fileName',
            field=models.TextField(default='empty'),
            preserve_default=False,
        ),
    ]
