# Generated by Django 2.2 on 2022-03-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JavaStepByStep', '0014_auto_20220305_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='project',
            new_name='projectId',
        ),
        migrations.AddField(
            model_name='file',
            name='projectId',
            field=models.TextField(default='empty'),
            preserve_default=False,
        ),
    ]
