# Generated by Django 2.2 on 2022-03-06 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JavaStepByStep', '0015_auto_20220306_2146'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
