# Generated by Django 2.2 on 2022-03-06 13:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('JavaStepByStep', '0016_auto_20220306_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('projectId', models.TextField(null=True)),
                ('commentator', models.CharField(max_length=50)),
                ('reviewed', models.CharField(max_length=50)),
                ('comment', models.TextField()),
                ('response', models.TextField(null=True)),
                ('comment_time', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('projectId', models.TextField()),
                ('owner', models.TextField()),
                ('fileName', models.TextField()),
                ('file_UploadTime', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
