# Generated by Django 2.2 on 2022-03-09 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JavaStepByStep', '0017_comment_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='fileName',
            new_name='filePath',
        ),
    ]
