# Generated by Django 2.2 on 2022-03-09 07:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('JavaStepByStep', '0018_auto_20220309_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('projectId', models.TextField()),
                ('commentator', models.CharField(max_length=50)),
                ('reviewed', models.CharField(max_length=50)),
                ('assign_CreateTime', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
