# Generated by Django 2.2 on 2022-03-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JavaStepByStep', '0019_assigncomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigncomment',
            name='commentatorScore',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
