# Generated by Django 2.2 on 2022-03-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JavaStepByStep', '0020_assigncomment_commentatorscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigncomment',
            name='haveDone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
