# Generated by Django 2.2 on 2022-03-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JavaStepByStep', '0021_assigncomment_havedone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigncomment',
            name='haveDone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
